import { HttpClientModule } from '@angular/common/http';
import { TestBed } from '@angular/core/testing';

import { Exercise } from '../models/exercise.model';
import { SimpleLog } from '../models/simple-log.model';
import {
    WorkoutPdfData,
    WorkoutPdfLabels,
    WorkoutPdfService
} from './workout-pdf.service';

describe('WorkoutPdfService', () => {
    let service: WorkoutPdfService;

    beforeEach(() => {
        TestBed.configureTestingModule({
            imports: [HttpClientModule]
        });
        service = TestBed.inject(WorkoutPdfService);
    });

    it('creates a populated PDF from a simple workout snapshot', async () => {
        const log = new SimpleLog();
        const strength = createExercise('Back Squat', true);
        strength.weight = 225;
        strength.reps = 5;
        strength.sets = 3;
        const cardio = createExercise('Bike', false);
        cardio.exerciseType = 'cardio';
        cardio.distance = 10;
        log.title = 'Saturday training';
        log.exercises = [strength];
        log.cardioExercises = [cardio];
        const addSection = spyOn<any>(service, 'addSection').and.callThrough();

        const pdf = await service.create(createPdfData(log));

        expect(pdf.output('arraybuffer').byteLength).toBeGreaterThan(1000);
        expect(pdf.getFont().fontName).toBe('NotoSans');
        expect(addSection.calls.count()).toBe(2);
        expect(addSection.calls.argsFor(0)[3]).toEqual([
            ['Back Squat', '225 lbs', '5', '3', 'Complete']
        ]);
        expect(addSection.calls.argsFor(1)[3][0][0]).toBe('Bike');
        expect(addSection.calls.argsFor(1)[3][0][1]).toBe('10 km');
    });

    it('uses localized labels and imported workout context', async () => {
        const log = new SimpleLog();
        const exercise = createExercise('Épaulé', false);
        exercise.prescription = '115 x 3 x 2';
        exercise.weight = '115';
        exercise.reps = '3';
        exercise.sets = '2';
        log.title = 'Semaine 1 - Journée 01';
        log.exercises = [exercise];
        const addSummary = spyOn<any>(service, 'addSummary').and.callThrough();
        const addSection = spyOn<any>(service, 'addSection').and.callThrough();
        const data = createPdfData(log, frenchLabels);
        data.locale = 'fr-CA';
        data.importedWorkout = {
            weekName: 'Semaine 1',
            dayName: 'Journée 01'
        };

        const pdf = await service.create(data);

        expect(pdf.output('arraybuffer').byteLength).toBeGreaterThan(1000);
        expect(addSummary).toHaveBeenCalled();
        expect(addSection.calls.argsFor(0)[1]).toBe('Musculation');
        expect(addSection.calls.argsFor(0)[2]).toContain('Prescription');
        expect(addSection.calls.argsFor(0)[3][0]).toEqual([
            'Épaulé', '115 x 3 x 2', '115 lbs', '3', '2', 'Incomplet'
        ]);
    });

    it('paginates a single oversized imported prescription', async () => {
        const log = new SimpleLog();
        const exercise = createExercise('Long complex', false);
        exercise.prescription = Array.from({ length: 450 }, () => 'clean + jerk').join(' ');
        log.exercises = [exercise];

        const pdf = await service.create(createPdfData(log));

        expect(pdf.getNumberOfPages()).toBeGreaterThan(1);
    });

    it('normalizes missing optional log values', async () => {
        const log = new SimpleLog();
        log.startDatim = undefined;
        log.exercises = undefined;
        log.cardioExercises = undefined;

        const pdf = await service.create(createPdfData(log));

        expect(pdf.output('arraybuffer').byteLength).toBeGreaterThan(1000);
    });

    it('creates a readable filename from the workout title and date', () => {
        const log = new SimpleLog();
        log.title = 'Saturday Training!';
        log.startDatim = new Date(2026, 5, 7, 10, 30);

        expect(service.getFileName(log)).toBe('saturday-training-2026-06-07.pdf');
    });
});

const englishLabels: WorkoutPdfLabels = {
    workoutLog: 'Workout Log',
    simpleWorkoutLog: 'Simple workout log',
    importedWorkout: 'Imported workout',
    strength: 'Strength',
    cardio: 'Cardio',
    exercise: 'Exercise',
    prescription: 'Prescription',
    weight: 'Weight',
    reps: 'Reps',
    sets: 'Sets',
    distance: 'Distance',
    duration: 'Duration',
    intensity: 'Intensity',
    status: 'Status',
    workoutDate: 'Workout date',
    elapsedTime: 'Elapsed time',
    units: 'Units',
    programWeek: 'Program week',
    programDay: 'Program day',
    complete: 'Complete',
    incomplete: 'Incomplete',
    completed: 'Completed',
    paused: 'Paused',
    inProgress: 'In progress',
    notStarted: 'Not started',
    notAvailable: 'N/A',
    generatedBy: 'Generated by Log Your Workout',
    page: 'Page',
    of: 'of',
    intensityNames: {
        1: 'Easy',
        2: 'Moderate',
        3: 'Hard',
        4: 'Maximal'
    }
};

const frenchLabels: WorkoutPdfLabels = {
    ...englishLabels,
    workoutLog: 'Journal d’entraînement',
    simpleWorkoutLog: 'Journal d’entraînement simple',
    importedWorkout: 'Entraînement importé',
    strength: 'Musculation',
    exercise: 'Exercice',
    weight: 'Poids',
    reps: 'Répétitions',
    sets: 'Séries',
    duration: 'Durée',
    intensity: 'Intensité',
    status: 'État',
    workoutDate: 'Date de l’entraînement',
    elapsedTime: 'Temps écoulé',
    units: 'Unités',
    programWeek: 'Semaine du programme',
    programDay: 'Jour du programme',
    complete: 'Terminé',
    incomplete: 'Incomplet',
    completed: 'Terminé',
    paused: 'En pause',
    inProgress: 'En cours',
    notStarted: 'Non commencé',
    notAvailable: 'S.O.',
    generatedBy: 'Généré par Log Your Workout',
    of: 'sur',
    intensityNames: {
        1: 'Facile',
        2: 'Modéré',
        3: 'Difficile',
        4: 'Maximal'
    }
};

function createPdfData(
    log: SimpleLog,
    labels: WorkoutPdfLabels = englishLabels
): WorkoutPdfData {
    return {
        log,
        weightMeasure: 'lbs',
        distanceMeasure: 'km',
        elapsedTimeLabel: '1h 5m',
        locale: 'en-CA',
        labels
    };
}

function createExercise(name: string, completed: boolean): Exercise {
    const exercise = new Exercise();
    exercise.exerciseType = 'strength';
    exercise.exerciseName = name;
    exercise.completed = completed;
    return exercise;
}
